controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

vue:
    path: /{vue_links}
    controller: App\Controller\HomeController::index
    requirements:
        vue_links: .*